### ISSUE TITLE
too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Ankit-Vohra** [renatoviolin/Bart_T5-summarization#1]
Trying to run your code. I have made a small change instead of using "cuda" I'm using "cpu" as I have few bugs in cuda. Now this error is rising. Can you also share a code snippet to run this directly on Python instead of using flask. 

`127.0.0.1 - - [02/Apr/2020 12:25:55] "GET / HTTP/1.1" 200 - 

127.0.0.1 - - [02/Apr/2020 12:26:04] "POST /predict HTTP/1.1" 500 -
{'message': 'too many values to unpack (expected 2)'}`

**Comment by parthplc** [comment]
I have the same issue when running on but only in case when I use BART.
T5 is working fine for me.
'message': 'too many values to unpack (expected 2)'

**Comment by Ankit-Vohra** [comment]
> I have the same issue when running on but only in case when I use BART.
> T5 is working fine for me.
> 'message': 'too many values to unpack (expected 2)'

I was able to resolve the issue by taking reference from: https://github.com/huggingface/transformers/issues/3508

Just add output_past=True while loading the pre-trained model
bart_model = BartForConditionalGeneration.from_pretrained(BART_PATH,output_past=True)

**Comment by renatoviolin** [comment]
I can't simulate this error. Are you using the same model bart-large or another one? Which version of transformers are you using? Mine is 2.7
