### ISSUE TITLE
Too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by RyanOngAI** [renatoviolin/Bart_T5-summarization#3]
Hey,

Great work on this! I am very interested in testing this out but I seem to be getting the above error whenever my beam search is greater than 1. With beam search set to 1, I am not able to really test out the model.

Could you please advise?

Thanks

Ryan

**Comment by AlexMikhalev** [comment]
Bump. 
Same here.
A

**Comment by renatoviolin** [comment]
Hi, 
I can't reproduce this error in my machine, event tough seems there's a bug in transformers lib.
To solve, just add output_past=True while loading the pre-trained model
bart_model = BartForConditionalGeneration.from_pretrained(BART_PATH,output_past=True)

I updated the repository adding this.

**Comment by RyanOngAI** [comment]
It works now with that changes. Thanks a lot :)
